
-- 题目6

GRANT ALL PRIVILEGES ON TABLE 学生,班级 TO U1 WITH GRANT OPTION;
GRANT SELECT,UPDATE(家庭住址)ON TABLE 学生 TO U2;
GRANT SELECT ON TABLE 班级 TO PUBLIC;
GRANT SELECT,UPDATE ON TABLE 学生 TO Rl;
GRANT R1 TO U1 WITH ADMIN OPTION;


-- 题目7

GRANT SELECT ON TABLE 职工,部门 TO 王明;
GRANT INSERT,DELETE ON TABLE 职工,部门 TO 李勇;
GRANT SELECT ON TABLE 职工 WHEN USER()= NAME TO ALL;
GRANT SELECT,UPDATE(工资)ON TABLE 职工 TO 刘星;
GRANT ALTER TABLE ON TABLE 职工,部门 TO 张新;
GRANT ALL PRIVILEGES ON TABLE 职工,部门 TO 周平 WITH GRANT OPTION;
CREATE VIEW 部门工资 AS
SELECT 部门.名称,MAX(工资).MIN(工资),AVG(工资) FROM职工,部门
WHERE 职工.部门号=部门.部门号 GROUP BY职工.部门号;
GRANT SELECT ON TABLE 部门工资 TO 杨兰;

-- 题目8

REVOKE SELECT ON TABLE 职工,部门 FROM 王明;
REVOKE INSERT,DELETE ON TABLE 职工,部门 FROM 李勇;
REOVKE SELECT ON TABLE 职工 WHEN USER()= NAME FROM ALL;
REVOKE SELECT,UPDATE ON TABLE 职工 FROM 刘星;
REVOKE ALTER TABLE ON TABLE 职工,部门 FROM 张新;
REVOKE ALL PRIVILEGES ON TABLE 职工,部门 FROM 周平;
REVOKE SELECT ON TABLE 部门工资 FROM 杨兰;
DROP VIEW 部门工资;