CREATE SCHEMA `db3.4`;
CREATE TABLE `db3.4`.S /*建S表*/
(SNO CHAR(3) PRIMARY KEY,
SNAME CHAR(10),
STATUS CHAR(2),
CITY CHAR(10));

CREATE TABLE `db3.4`.P /*建P表*/
(PNO CHAR(3) PRIMARY KEY,
PNAME CHAR(10),
COLOR CHAR(4),
WEIGHT INT);

CREATE TABLE `db3.4`.J /*建J表*/ 
(JNO CHAR(3) PRIMARY KEY,
JNAME CHAR(10),
CITY CHAR(10));

CREATE TABLE `db3.4`.SPJ /*建SPJ表*/
(SNO CHAR(3),
PNO CHAR(3),
JNO CHAR(3),
QTY INT,
ID CHAR(3) PRIMARY KEY);