USE `db3.4`;
/*找出所有供应商的姓名和所在城市*/
SELECT SNAME,CITY FROM S;

/*找出所有零件的名称、颜色、重量*/
SELECT PNAME,COLOR,WEIGHT FROM P;

/*找出使用供应商S1所提供零件的工程号码*/
SELECT JNO FROM SPJ WHERE SNO='S1';

/*找出工程项目J2使用的各种零件名称及数量*/
SELECT P.PNAME,SPJ.QTY FROM P,SPJ
WHERE P.PNO=SPJ.PNO AND SPJ.JNO='J2';

/*找出上海厂商供应的所有零件号码*/
SELECT DISTINCT PNO FROM SPJ 
WHERE SNO IN (SELECT SNO FROM S
WHERE S.CITY='上海');

/*找出使用上海产的零件的工程名称*/
SELECT DISTINCT JNAME FROM J,SPJ,S
WHERE J.JNO=SPJ.JNO AND SPJ.SNO=S.SNO
AND S.CITY='上海';

/*找出没有使用天津产的零件的工程号码*/
SELECT JNO FROM J WHERE NOT EXISTS
(SELECT *FROM SPJ,S
WHERE SPJ.JNO=J.JNO AND SPJ.SNO=S.SNO
AND S.CITY='天津');

/*把全部红色零件的颜色改成蓝色*/
SET SQL_SAFE_UPDATES = 0;
UPDATE P SET COLOR='蓝'
WHERE COLOR='红';

/*由S5供给J4的零件P6改为由S3供应*/
UPDATE SPJ SET SNO='S3'
WHERE SNO='S5' AND JNO='J4' AND PNO='P6';

/*从供应商关系中删除S2的记录，并从供应情况关系中删除相应的记录*/
/*注意删除顺序，应先从SPJ表中删除供应商S2所提供零件记录，再在S表中删除*/
DELETE FROM SPJ WHERE SNO='S2';
DELETE FROM S WHERE SNO='S2';

/*请将（S2,J6,P4,200）插入供应情况关系*/
INSERT INTO `db3.4`.`spj`  VALUES ('S2', 'J6', 'P4', '200', '20');